default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --check
        language: system
        files: '\.rs$'
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        files: '(^|/)(Cargo\.(toml|lock)|.*\.rs)$'
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        entry: cargo test --all-features
        language: system
        stages: [pre-push]
        pass_filenames: false
