/// Stable version 1 installation error catalog.
pub const INSTALL_ERRORS: &[&str] = &[
    "json.invalid_request",
    "json.unsupported_schema_version",
    "install.approval_required",
    "install.write_failed",
];

/// Stable version 1 installation action catalog.
pub const INSTALL_ACTIONS: &[&str] = &["file.write", "install.approve"];

use std::{
    env,
    ffi::OsStr,
    fs::{self, OpenOptions},
    io::Write,
    os::unix::{
        ffi::OsStrExt,
        fs::{MetadataExt, PermissionsExt},
        process::ExitStatusExt,
    },
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use anyhow::{Context, Result, bail};
use cliclack::{confirm, input, select};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::{
    config,
    protocol::{
        self, BytePath, Effect, ErrorBody, MutationClass, RecoveryAction, RecoveryInvocation,
    },
    ui,
};

const START_MARKER: &[u8] = b"# >>> pando shell integration >>>";
const END_MARKER: &[u8] = b"# <<< pando shell integration <<<";
const CONFIG_START_MARKER: &[u8] = b"# >>> pando configuration scaffold >>>";
const CONFIG_END_MARKER: &[u8] = b"# <<< pando configuration scaffold <<<";
const INSTALL_START_MARKER: &[u8] = b"# >>> pando guided installer >>>";
const INSTALL_END_MARKER: &[u8] = b"# <<< pando guided installer <<<";

const CONFIG_SCAFFOLD: &[u8] = br"# >>> pando configuration scaffold >>>
# Uncomment and customize these settings as needed.
#
# Worktree creation requires a placement root:
# worktrees:
#   root: ../worktrees
#   # Optional target branch. If omitted, Pando falls back to origin/HEAD,
#   # then local main, then local master:
#   target-branch: main
#
# Optional PR metadata generator. Required only when title or description is
# omitted from `pando pr create`:
# pr:
#   # auto uses gh for github.com and tea for a matching Gitea/Forgejo login.
#   provider: auto
#   generation:
#     command: pi --no-session --no-tools
# <<< pando configuration scaffold <<<
";

const INTEGRATION: &[u8] = br#"# Generated by pando. Do not edit.
# The dispatcher deliberately avoids a leading underscore: that prefix is the
# zsh completion-function convention, and tools that capture a shell's function
# table (Claude Code's shell snapshots, for one) drop `_name` functions wholesale
# to skip the completion system. A dropped helper would leave `pando` and
# `pd` defined but calling a command that no longer exists.
pando_dispatch() {
  local executable="$1"
  shift
  local structured=false passthrough=false expect_format=false arg
  for arg in "$@"; do
    if [[ "$expect_format" == true ]]; then
      [[ "$arg" == json ]] && structured=true
      expect_format=false
      continue
    fi
    case "$arg" in
      --output|--input-output) expect_format=true ;;
      --output=json|--input-output=json) structured=true ;;
      -h|--help|-V|--version) passthrough=true ;;
    esac
  done
  if [[ ! -o interactive ]] || [[ "$structured" == true ]] || [[ "$passthrough" == true ]]; then
    command "$executable" "$@"
  elif [[ "$1" == "switch" || "$1" == "create" || "$1" == "remove" || "$1" == "merge" ]]; then
    local destination
    destination="$(command "$executable" "$@")"
    local exit_status=$?
    if [[ -n "$destination" ]]; then
      builtin cd -- "$destination" || return $?
    fi
    return $exit_status
  else
    command "$executable" "$@"
  fi
}

pando() { pando_dispatch pando "$@"; }
pd() { pando_dispatch pd "$@"; }

# Dynamic completion for both names. The registration script is generated on
# every shell start rather than cached: clap_complete gives no stability
# guarantee between the script it emits and the completion protocol the binary
# expects, so a cached script would silently break after a binary upgrade.
# Generating it costs one process spawn, measured under 3ms.
#
# `pd` is a symlink to the same binary, so one registration serves both names.
# The generated function is named `_clap_dynamic_completer_pando`; the
# leading underscore is the completion system's own convention here, unlike the
# dispatcher above, and a dropped snapshot copy only disables completion.
pando_register_completion() {
  (( $+functions[compdef] )) || return 1
  local script
  # Captured into a variable rather than `eval "$(... )"` directly: if the
  # binary is missing from PATH the command substitution yields an empty
  # string, and `eval ""` exits 0. That would report registration as
  # successful while leaving `_clap_dynamic_completer_pando` undefined,
  # so `compdef` below would bind both names to a function that never
  # existed and the precmd retry would never re-arm.
  script="$(_PANDO_COMPLETE=zsh command pando 2>/dev/null)" || return 1
  [[ -n "$script" ]] || return 1
  eval "$script"
  compdef _clap_dynamic_completer_pando pd
  return 0
}

if [[ -o interactive ]]; then
  if ! pando_register_completion; then
    # `compinit` has not run yet, so retry once after startup finishes.
    pando_deferred_completion() {
      pando_register_completion
      add-zsh-hook -d precmd pando_deferred_completion
      unfunction pando_deferred_completion
    }
    autoload -Uz add-zsh-hook && add-zsh-hook precmd pando_deferred_completion
  fi
fi
"#;

#[derive(Clone, Debug, Default, Deserialize, JsonSchema, Serialize)]
#[serde(deny_unknown_fields)]
pub struct InstallInput {
    #[serde(default)]
    pub dry_run: bool,
}

#[derive(Clone, Debug, JsonSchema, Serialize)]
pub struct InstallTarget {
    pub path: BytePath,
    pub would_change: bool,
}

/// Deterministic filesystem changes shared by installation adapters.
#[derive(Clone, Debug, JsonSchema, Serialize)]
pub struct InstallPlan {
    pub changed: bool,
    pub configuration: InstallTarget,
    pub integration: InstallTarget,
    pub startup: InstallTarget,
    #[serde(skip)]
    config_path: PathBuf,
    #[serde(skip)]
    integration_path: PathBuf,
    #[serde(skip)]
    startup_path: PathBuf,
}

#[derive(Debug, JsonSchema, Serialize)]
#[serde(tag = "outcome", rename_all = "snake_case")]
pub enum InstallResult {
    DryRun { plan: InstallPlan },
    AlreadyCurrent { plan: InstallPlan },
    Installed { plan: InstallPlan },
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct FileIdentity {
    device: u64,
    inode: u64,
    mode: u32,
}

#[derive(Clone, Debug, Eq, PartialEq)]
enum TargetObservation {
    Absent {
        ancestor_path: PathBuf,
        ancestor: PathBuf,
        ancestor_identity: FileIdentity,
    },
    File {
        identity: FileIdentity,
        content: Vec<u8>,
    },
    Symlink {
        identity: FileIdentity,
        link: PathBuf,
        destination: PathBuf,
        destination_identity: FileIdentity,
        content: Vec<u8>,
    },
}

#[derive(Debug)]
struct ProposedWrite {
    role: &'static str,
    path: PathBuf,
    desired: Vec<u8>,
    observed: TargetObservation,
    verb: &'static str,
}

#[derive(Debug)]
struct InstallProposal {
    writes: Vec<ProposedWrite>,
}

struct InstallApproval(());

/// Non-authoritative observations emitted during deterministic installation and guidance.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) enum Observation {
    FileWritten { role: &'static str },
    ShellInstalled { startup_path: PathBuf },
    ShellCurrent,
    GuidanceCommandSaved { config_path: PathBuf },
    GuidanceLaunching { command: String },
    GuidanceDeclined,
    GuidanceCompleted,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum Delivery {
    Human,
    #[cfg(test)]
    Captured,
}

pub(crate) struct Observations {
    delivery: Delivery,
    events: Vec<Observation>,
}

impl Observations {
    #[must_use]
    pub(crate) const fn human() -> Self {
        Self {
            delivery: Delivery::Human,
            events: Vec::new(),
        }
    }

    #[cfg(test)]
    #[must_use]
    const fn captured() -> Self {
        Self {
            delivery: Delivery::Captured,
            events: Vec::new(),
        }
    }

    pub(crate) fn emit(&mut self, observation: Observation) {
        if matches!(self.delivery, Delivery::Human) {
            let _ = render_observation(&observation);
        }
        self.events.push(observation);
    }

    /// Completes infallible, presentation-only observation delivery.
    #[must_use]
    pub(crate) fn finish(self) -> Vec<Observation> {
        self.events
    }
}

fn render_observation(observation: &Observation) -> Result<()> {
    match observation {
        Observation::FileWritten { .. } => Ok(()),
        Observation::ShellInstalled { startup_path } => {
            ui::success("Installed zsh integration.")?;
            ui::info(format!(
                "Restart zsh or run: source {}",
                ui::worktree_data_style().apply_to(startup_path.display())
            ))
        }
        Observation::ShellCurrent => ui::info("The Pando shell integration is already current."),
        Observation::GuidanceCommandSaved { config_path } => ui::step(format!(
            "saved guided installer command in {}",
            ui::worktree_data_style().apply_to(config_path.display())
        )),
        Observation::GuidanceLaunching { command } => ui::info(format!(
            "Launching {} for guided configuration...",
            ui::worktree_data_style().apply_to(command)
        )),
        Observation::GuidanceDeclined => {
            ui::warning("Guided configuration declined; the agent command was not saved.")
        }
        Observation::GuidanceCompleted => ui::success("Guided configuration session completed."),
    }
}

struct InstallAssessment {
    plan: InstallPlan,
    proposal: InstallProposal,
}

#[derive(Debug)]
pub struct InstallFailure {
    code: &'static str,
    message: String,
}

impl From<InstallFailure> for ErrorBody {
    fn from(failure: InstallFailure) -> Self {
        Self {
            code: failure.code.into(),
            message: failure.message,
        }
    }
}

/// Command-owned result consumed by the human and JSON adapters.
#[derive(Debug)]
pub struct InstallOutcome {
    pub result: std::result::Result<InstallResult, InstallFailure>,
    pub effects: Vec<Effect>,
    pub recovery: Vec<RecoveryAction<protocol::EmptyInput>>,
    completion: Option<InstallCompletion>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum InstallCompletion {
    ShellInstalled,
    AlreadyCurrent,
    Guided,
    GuidanceDeclined,
}

/// Builds one deterministic installation assessment and its opaque proposal.
fn assess() -> Result<InstallAssessment> {
    let config_path = config_home()?.join("pando/config.yaml");
    let integration_path = config_home()?.join("pando/pando.zsh");
    let startup_path = zshrc_path()?;
    let source_block = source_block(&integration_path);
    let observed_config = observe_target(&config_path)?;
    let observed_integration = observe_target(&integration_path)?;
    let observed_startup = observe_target(&startup_path)?;
    let existing_config = observed_config.content();
    let existing_integration = observed_integration.content();
    let existing_startup = observed_startup.content();
    let desired_config = update_config_scaffold(existing_config)?;
    let desired_startup = update_source_block(existing_startup, &source_block)?;
    let configuration_changed = existing_config != desired_config;
    let integration_changed = existing_integration != INTEGRATION;
    let startup_changed = existing_startup != desired_startup;
    let plan = InstallPlan {
        changed: configuration_changed || integration_changed || startup_changed,
        configuration: InstallTarget {
            path: BytePath::path(&config_path),
            would_change: configuration_changed,
        },
        integration: InstallTarget {
            path: BytePath::path(&integration_path),
            would_change: integration_changed,
        },
        startup: InstallTarget {
            path: BytePath::path(&startup_path),
            would_change: startup_changed,
        },
        config_path: config_path.clone(),
        integration_path: integration_path.clone(),
        startup_path: startup_path.clone(),
    };
    let writes = [
        (
            configuration_changed,
            "configuration",
            config_path,
            desired_config,
            observed_config,
            "update",
        ),
        (
            integration_changed,
            "integration",
            integration_path,
            INTEGRATION.to_vec(),
            observed_integration,
            "write",
        ),
        (
            startup_changed,
            "startup",
            startup_path,
            desired_startup,
            observed_startup,
            "update",
        ),
    ]
    .into_iter()
    .filter_map(|(changed, role, path, desired, observed, verb)| {
        changed.then_some(ProposedWrite {
            role,
            path,
            desired,
            observed,
            verb,
        })
    })
    .collect();
    Ok(InstallAssessment {
        plan,
        proposal: InstallProposal { writes },
    })
}

impl TargetObservation {
    fn content(&self) -> &[u8] {
        match self {
            Self::Absent { .. } => &[],
            Self::File { content, .. } | Self::Symlink { content, .. } => content,
        }
    }
}

fn file_identity(metadata: &fs::Metadata) -> FileIdentity {
    FileIdentity {
        device: metadata.dev(),
        inode: metadata.ino(),
        mode: metadata.mode(),
    }
}

fn observe_target(path: &Path) -> Result<TargetObservation> {
    let metadata = match fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            let ancestor = nearest_existing_ancestor(path)?;
            let ancestor_metadata = fs::metadata(&ancestor).with_context(|| {
                format!(
                    "failed to inspect destination ancestor {}",
                    ancestor.display()
                )
            })?;
            return Ok(TargetObservation::Absent {
                ancestor_path: ancestor.clone(),
                ancestor: fs::canonicalize(&ancestor).with_context(|| {
                    format!(
                        "failed to resolve destination ancestor {}",
                        ancestor.display()
                    )
                })?,
                ancestor_identity: file_identity(&ancestor_metadata),
            });
        }
        Err(error) => {
            return Err(error)
                .with_context(|| format!("failed to inspect destination {}", path.display()));
        }
    };
    if !metadata.file_type().is_symlink() {
        return Ok(TargetObservation::File {
            identity: file_identity(&metadata),
            content: fs::read(path)
                .with_context(|| format!("failed to read existing file {}", path.display()))?,
        });
    }
    let link = fs::read_link(path)
        .with_context(|| format!("failed to inspect symlink {}", path.display()))?;
    let destination = fs::canonicalize(path)
        .with_context(|| format!("refusing to replace broken symlink {}", path.display()))?;
    let destination_metadata = fs::metadata(&destination)
        .with_context(|| format!("failed to inspect destination {}", destination.display()))?;
    Ok(TargetObservation::Symlink {
        identity: file_identity(&metadata),
        link,
        destination,
        destination_identity: file_identity(&destination_metadata),
        content: fs::read(path)
            .with_context(|| format!("failed to read existing file {}", path.display()))?,
    })
}

fn observation_matches(path: &Path, observed: &TargetObservation) -> Result<bool> {
    let TargetObservation::Absent {
        ancestor_path,
        ancestor,
        ancestor_identity,
    } = observed
    else {
        return Ok(observe_target(path)? == *observed);
    };
    match fs::symlink_metadata(path) {
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Ok(_) => return Ok(false),
        Err(error) => return Err(error.into()),
    }
    let metadata = fs::metadata(ancestor_path)?;
    if file_identity(&metadata) != *ancestor_identity
        || fs::canonicalize(ancestor_path)? != *ancestor
    {
        return Ok(false);
    }
    let relative_parent = path
        .parent()
        .and_then(|parent| parent.strip_prefix(ancestor_path).ok())
        .context("installation target escaped its observed ancestor")?;
    let mut current = ancestor_path.clone();
    for component in relative_parent.components() {
        current.push(component);
        match fs::symlink_metadata(&current) {
            Ok(metadata) if metadata.is_dir() && !metadata.file_type().is_symlink() => {}
            Ok(_) => return Ok(false),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => break,
            Err(error) => return Err(error.into()),
        }
    }
    Ok(true)
}

fn nearest_existing_ancestor(path: &Path) -> Result<PathBuf> {
    let mut candidate = path.parent().context("installation target has no parent")?;
    loop {
        match fs::metadata(candidate) {
            Ok(_) => return Ok(candidate.to_path_buf()),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                candidate = candidate
                    .parent()
                    .context("installation target has no existing ancestor")?;
            }
            Err(error) => {
                return Err(error).with_context(|| {
                    format!(
                        "failed to inspect destination ancestor {}",
                        candidate.display()
                    )
                });
            }
        }
    }
}

/// Builds the deterministic, non-executable installation plan.
///
/// # Errors
/// Returns an error when paths or existing installation files cannot be read.
pub fn plan() -> Result<InstallPlan> {
    Ok(assess()?.plan)
}

fn write_effect(write: &ProposedWrite) -> Effect {
    Effect {
        action: "file.write".into(),
        attempted: false,
        completed: false,
        details: Some(serde_json::json!({
            "target": BytePath::path(&write.path),
            "role": write.role,
        })),
    }
}

fn effects(proposal: &InstallProposal) -> Vec<Effect> {
    proposal.writes.iter().map(write_effect).collect()
}

/// Returns the typed non-mutating outcome for structured installation.
///
/// # Errors
/// Returns an error when the installation plan cannot be inspected.
pub fn inspect(input: &InstallInput) -> Result<InstallOutcome> {
    let InstallAssessment { plan, proposal } = assess()?;
    if !plan.changed {
        return Ok(InstallOutcome {
            result: Ok(InstallResult::AlreadyCurrent { plan }),
            effects: Vec::new(),
            recovery: Vec::new(),
            completion: None,
        });
    }
    let planned_effects = effects(&proposal);
    if input.dry_run {
        return Ok(InstallOutcome {
            result: Ok(InstallResult::DryRun { plan }),
            effects: planned_effects,
            recovery: Vec::new(),
            completion: None,
        });
    }
    Ok(InstallOutcome {
        result: Err(InstallFailure {
            code: "install.approval_required",
            message: "installation requires a manual human invocation".into(),
        }),
        effects: planned_effects,
        recovery: vec![RecoveryAction {
            action: "install.approve".into(),
            description: "Review and approve installation interactively".into(),
            mutation: MutationClass::Filesystem,
            requires_human_approval: true,
            invocation: RecoveryInvocation {
                argv: vec!["pando".into(), "install".into()],
                stdin: None,
                working_directory: None,
            },
        }],
        completion: None,
    })
}

/// Renders the installation plan without writing or prompting.
///
/// # Errors
/// Returns an error when paths or existing installation files cannot be read or rendered.
pub fn preview() -> Result<()> {
    let InstallAssessment { plan, .. } = assess()?;
    ui::info(ui::heading_style().apply_to("Planned zsh integration changes:"))?;
    for (path, changed) in [
        (&plan.integration_path, plan.integration.would_change),
        (&plan.startup_path, plan.startup.would_change),
    ] {
        let state = if changed {
            "would update"
        } else {
            "already current"
        };
        ui::step(format!(
            "{state}: {}",
            ui::worktree_data_style().apply_to(path.display())
        ))?;
    }
    ui::finish(ui::success_style().apply_to("Installation preview complete."))
}

/// Installs or updates the managed zsh integration after confirmation.
///
/// When `guided` is true, the deterministic shell installation is followed by
/// an interactive agent selector and an LLM-guided configuration session.
///
/// # Errors
///
/// Returns an error when environment paths cannot be resolved, existing files
/// cannot be inspected, confirmation cannot be read, a planned write fails, or
/// the selected agent cannot complete its session.
pub fn run(guided: bool) -> Result<()> {
    let InstallAssessment { plan, proposal } = assess()?;
    if plan.changed {
        ui::ensure_interactive("Pando installation requires confirmation")?;
        ui::info(ui::heading_style().apply_to("Planned Pando installation changes:"))?;
        for (verb, path, changed) in [
            ("write", &plan.config_path, plan.configuration.would_change),
            (
                "write",
                &plan.integration_path,
                plan.integration.would_change,
            ),
            ("update", &plan.startup_path, plan.startup.would_change),
        ] {
            if changed {
                ui::step(format!(
                    "{verb} {}",
                    ui::worktree_data_style().apply_to(path.display())
                ))?;
            }
        }

        let confirmed = ui::prompt_result(
            confirm("Apply these changes?")
                .initial_value(false)
                .interact(),
            "installation cancelled",
            "failed to read installation confirmation",
        )?;
        if !confirmed {
            return Err(ui::declined_noop(
                "Installation declined; no files were changed.",
                "Zsh integration was not installed.",
            ));
        }
    }

    let mut observations = Observations::human();
    let outcome = execute(
        proposal,
        InstallApproval(()),
        plan,
        guided,
        &mut observations,
    );
    drop(observations.finish());
    finish_human_install(outcome)
}

fn finish_human_install(outcome: InstallOutcome) -> Result<()> {
    if let Err(failure) = outcome.result {
        bail!(failure.message);
    }
    let (completion, style) = match outcome
        .completion
        .expect("human installation records its presentation completion")
    {
        InstallCompletion::ShellInstalled => ("Zsh integration installed.", ui::success_style()),
        InstallCompletion::AlreadyCurrent => (
            "Pando installation is already current.",
            ui::success_style(),
        ),
        InstallCompletion::Guided => (
            "Pando installation and configuration complete.",
            ui::success_style(),
        ),
        InstallCompletion::GuidanceDeclined => (
            "Zsh integration installed without guided configuration.",
            ui::warning_style(),
        ),
    };
    let _ = ui::finish(style.apply_to(completion));
    Ok(())
}

fn execute(
    proposal: InstallProposal,
    _approval: InstallApproval,
    plan: InstallPlan,
    guided: bool,
    observations: &mut Observations,
) -> InstallOutcome {
    let shell_changed = plan.changed;
    let mut effects = effects(&proposal);
    for (index, write) in proposal.writes.into_iter().enumerate() {
        match observation_matches(&write.path, &write.observed) {
            Ok(true) => {}
            Ok(false) => {
                return install_failure(
                    effects,
                    format!(
                        "refusing to {} {} because it changed after approval",
                        write.verb,
                        write.path.display()
                    ),
                );
            }
            Err(error) => {
                return install_failure(
                    effects,
                    format!(
                        "failed to revalidate {} before {}: {error:#}",
                        write.path.display(),
                        write.verb
                    ),
                );
            }
        }
        effects[index].attempted = true;
        if let Err(error) = write_observed_target(&write.path, &write.observed, &write.desired) {
            return install_failure(
                effects,
                format!(
                    "failed to {} {}: {error:#}",
                    write.verb,
                    write.path.display()
                ),
            );
        }
        effects[index].completed = true;
        observations.emit(Observation::FileWritten { role: write.role });
    }
    if shell_changed {
        observations.emit(Observation::ShellInstalled {
            startup_path: plan.startup_path.clone(),
        });
    } else {
        observations.emit(Observation::ShellCurrent);
    }
    let completion = if guided {
        match run_guided_configuration(&plan.config_path, observations, &mut effects) {
            Ok(GuidanceCompletion::Completed) => InstallCompletion::Guided,
            Ok(GuidanceCompletion::Declined) => InstallCompletion::GuidanceDeclined,
            Err(error) => return install_failure(effects, format!("{error:#}")),
        }
    } else if shell_changed {
        InstallCompletion::ShellInstalled
    } else {
        InstallCompletion::AlreadyCurrent
    };
    InstallOutcome {
        result: Ok(if shell_changed {
            InstallResult::Installed { plan }
        } else {
            InstallResult::AlreadyCurrent { plan }
        }),
        effects,
        recovery: Vec::new(),
        completion: Some(completion),
    }
}

fn install_failure(effects: Vec<Effect>, message: String) -> InstallOutcome {
    InstallOutcome {
        result: Err(InstallFailure {
            code: "install.write_failed",
            message,
        }),
        effects,
        recovery: Vec::new(),
        completion: None,
    }
}

#[derive(Clone, Copy)]
struct KnownAgent {
    executable: &'static str,
    label: &'static str,
    command: &'static str,
}

const KNOWN_AGENTS: [KnownAgent; 4] = [
    KnownAgent {
        executable: "pi",
        label: "Pi",
        command: "pi",
    },
    KnownAgent {
        executable: "claude",
        label: "Claude Code",
        command: "claude",
    },
    KnownAgent {
        executable: "codex",
        label: "Codex",
        command: "codex",
    },
    KnownAgent {
        executable: "gemini",
        label: "Gemini CLI",
        command: "gemini",
    },
];

struct AgentChoice {
    label: String,
    hint: &'static str,
    command: String,
}

struct GuidanceSelection {
    command: String,
    config_observation: TargetObservation,
    saved_command: Option<String>,
}

#[derive(Debug, Eq, PartialEq)]
enum AgentCompletion {
    Completed,
    Interrupted,
    Failed(String),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum GuidanceCompletion {
    Completed,
    Declined,
}

fn run_guided_configuration(
    config_path: &Path,
    observations: &mut Observations,
    effects: &mut Vec<Effect>,
) -> Result<GuidanceCompletion> {
    let selection = select_guidance(config_path)?;
    let command_write = propose_install_command(config_path, selection)?;

    let confirmed = ui::prompt_result(
        confirm("Save this command and start guided configuration?")
            .initial_value(true)
            .interact(),
        "guided configuration cancelled",
        "failed to read guided configuration confirmation",
    )?;
    if !confirmed {
        observations.emit(Observation::GuidanceDeclined);
        return Ok(GuidanceCompletion::Declined);
    }

    let command = command_write.command.clone();
    let effect_index = command_write.write.as_ref().map(|write| {
        effects.push(write_effect(write));
        effects.len() - 1
    });
    persist_proposed_command(
        &command_write,
        effect_index.and_then(|index| effects.get_mut(index)),
    )?;
    observations.emit(Observation::GuidanceCommandSaved {
        config_path: config_path.to_path_buf(),
    });

    let cwd = env::current_dir().context("failed to resolve the guided session directory")?;
    let prompt = guided_prompt(config_path, &cwd, &command);
    observations.emit(Observation::GuidanceLaunching {
        command: command.clone(),
    });
    match run_agent(&command, &prompt, &cwd) {
        AgentCompletion::Completed => {
            observations.emit(Observation::GuidanceCompleted);
            Ok(GuidanceCompletion::Completed)
        }
        AgentCompletion::Interrupted => bail!("guided configuration agent was interrupted"),
        AgentCompletion::Failed(message) => bail!(message),
    }
}

fn select_guidance(config_path: &Path) -> Result<GuidanceSelection> {
    ui::ensure_interactive("guided Pando configuration requires an interactive terminal")?;
    let config_observation = observe_target(config_path)?;
    let saved_command = config::load_install_command(config_path)?;
    if !observation_matches(config_path, &config_observation)? {
        bail!("global configuration changed while preparing guided configuration");
    }
    let choices = agent_choices(saved_command.as_deref());
    let mut selector = select("Choose your connected LLM agent")
        .initial_value(0)
        .max_rows(6);
    for (index, choice) in choices.iter().enumerate() {
        selector = selector.item(index, &choice.label, choice.hint);
    }
    let selected = ui::prompt_result(
        selector.interact(),
        "agent selection cancelled",
        "failed to read the agent selection",
    )?;
    let default_command = &choices[selected].command;
    let mut command_prompt = input("Command to launch the agent").validate(|value: &String| {
        validate_agent_command(value).map_err(|error| error.to_string())
    });
    if !default_command.is_empty() {
        command_prompt = command_prompt.default_input(default_command);
    }
    let command: String = ui::prompt_result(
        command_prompt.interact(),
        "agent command entry cancelled",
        "failed to read the agent command",
    )?;
    Ok(GuidanceSelection {
        command: command.trim().to_owned(),
        config_observation,
        saved_command,
    })
}

struct CommandWrite {
    command: String,
    write: Option<ProposedWrite>,
}

fn propose_install_command(
    config_path: &Path,
    selection: GuidanceSelection,
) -> Result<CommandWrite> {
    let desired = persist_install_command(
        selection.config_observation.content(),
        selection.saved_command.as_deref(),
        &selection.command,
    )?;
    let write = (selection.config_observation.content() != desired).then(|| ProposedWrite {
        role: "guided command",
        path: config_path.to_path_buf(),
        desired,
        observed: selection.config_observation,
        verb: "update",
    });
    Ok(CommandWrite {
        command: selection.command,
        write,
    })
}

fn persist_proposed_command(proposal: &CommandWrite, effect: Option<&mut Effect>) -> Result<()> {
    let Some(write) = proposal.write.as_ref() else {
        debug_assert!(effect.is_none());
        return Ok(());
    };
    let effect = effect.expect("a proposed guided command write has an effect");
    if !observation_matches(&write.path, &write.observed)? {
        bail!(
            "refusing to update {} because it changed after confirmation",
            write.path.display()
        );
    }
    effect.attempted = true;
    write_observed_target(&write.path, &write.observed, &write.desired)
        .with_context(|| format!("failed to update {}", write.path.display()))?;
    effect.completed = true;
    Ok(())
}

fn agent_choices(saved_command: Option<&str>) -> Vec<AgentChoice> {
    let mut choices = Vec::new();
    if let Some(saved) = saved_command {
        let label = KNOWN_AGENTS
            .iter()
            .find(|agent| agent.command == saved)
            .map_or_else(
                || "Saved command".to_owned(),
                |agent| format!("{} (saved)", agent.label),
            );
        choices.push(AgentChoice {
            label,
            hint: "from global config",
            command: saved.to_owned(),
        });
    }
    for agent in KNOWN_AGENTS {
        if saved_command == Some(agent.command) || !executable_on_path(agent.executable) {
            continue;
        }
        choices.push(AgentChoice {
            label: agent.label.to_owned(),
            hint: "detected on PATH",
            command: agent.command.to_owned(),
        });
    }
    choices.push(AgentChoice {
        label: "Custom command".to_owned(),
        hint: "enter another agent CLI",
        command: String::new(),
    });
    choices
}

fn executable_on_path(name: &str) -> bool {
    env::var_os("PATH").is_some_and(|path| {
        env::split_paths(&path).any(|directory| {
            fs::metadata(directory.join(name)).is_ok_and(|metadata| {
                metadata.is_file() && metadata.permissions().mode() & 0o111 != 0
            })
        })
    })
}

fn guided_prompt(config_path: &Path, cwd: &Path, command: &str) -> String {
    format!(
        "You are guiding the user through a complete Pando installation and configuration. \
The deterministic zsh integration is already installed. Continue as an interactive conversation: \
inspect the local environment, explain each relevant choice, ask the user for preferences, and use \
your file tools to update the global YAML config at {config_path}. Preserve both Pando-managed marker \
blocks exactly, including install.command, which must remain {command:?}. Configure the full useful \
global surface as appropriate: worktrees.root, worktrees.default-sort, worktrees.base, \
worktrees.target-branch, commit.generation, merge.squash and merge.generation, pr.provider, \
pr.generation, and pr.pull-request-template. Values are strict YAML. default-sort accepts git, branch, \
last-commit-at, or path; base accepts head or fresh; pr.provider accepts auto, github, or tea. Global \
configuration cannot define hooks. If the current directory {cwd} is in a Git repository, you may \
also explain the committed .pando.yaml and ignored .pando.local.yaml layers, but edit them only after \
explicit user approval. Never overwrite unrelated settings or comments. Validate the resulting YAML \
and finish by summarizing what you changed and any commands the user still needs to run.",
        config_path = config_path.display(),
        cwd = cwd.display(),
    )
}

fn run_agent(command: &str, prompt: &str, cwd: &Path) -> AgentCompletion {
    let agent_stdout = match OpenOptions::new().write(true).open("/dev/stderr") {
        Ok(stderr) => Stdio::from(stderr),
        Err(error) => {
            return AgentCompletion::Failed(format!(
                "failed to open stderr for the guided configuration agent: {error}"
            ));
        }
    };
    let invocation = match agent_invocation(command, prompt) {
        Ok(invocation) => invocation,
        Err(error) => return AgentCompletion::Failed(error.to_string()),
    };
    let status = Command::new("/bin/sh")
        .args(["-c", &invocation])
        .current_dir(cwd)
        .stdin(Stdio::inherit())
        .stdout(agent_stdout)
        .stderr(Stdio::inherit())
        .status();
    let status = match status {
        Ok(status) => status,
        Err(error) => {
            return AgentCompletion::Failed(format!(
                "failed to start the guided configuration agent: {error}"
            ));
        }
    };
    if status.success() {
        return AgentCompletion::Completed;
    }
    if status
        .signal()
        .is_some_and(|signal| matches!(signal, 2 | 3 | 15))
    {
        return AgentCompletion::Interrupted;
    }
    AgentCompletion::Failed(format!("guided configuration agent failed with {status}"))
}

fn validate_agent_command(command: &str) -> Result<()> {
    let command = command.trim();
    if command.is_empty() {
        bail!("agent command cannot be empty");
    }
    let placeholders = command.matches("{prompt}").count();
    if placeholders > 1 {
        bail!("agent command may contain at most one {{prompt}} placeholder");
    }
    if placeholders == 0 && command.chars().any(|value| "|&;<>\n\r".contains(value)) {
        bail!(
            "commands with shell operators must place {{prompt}} where the agent should receive it"
        );
    }
    Ok(())
}

fn agent_invocation(command: &str, prompt: &str) -> Result<String> {
    validate_agent_command(command)?;
    let prompt = shell_quote(prompt);
    if command.contains("{prompt}") {
        return Ok(format!("exec {}", command.replace("{prompt}", &prompt)));
    }
    Ok(format!("exec {command} {prompt}"))
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

#[derive(Serialize)]
struct ManagedInstallConfig<'a> {
    install: ManagedInstallCommand<'a>,
}

#[derive(Serialize)]
struct ManagedInstallCommand<'a> {
    command: &'a str,
}

fn install_command_block(command: &str) -> Result<Vec<u8>> {
    let yaml = serde_yaml::to_string(&ManagedInstallConfig {
        install: ManagedInstallCommand { command },
    })?;
    Ok([
        INSTALL_START_MARKER,
        b"\n",
        yaml.as_bytes(),
        INSTALL_END_MARKER,
        b"\n",
    ]
    .concat())
}

fn persist_install_command(
    existing: &[u8],
    saved_command: Option<&str>,
    command: &str,
) -> Result<Vec<u8>> {
    let has_managed_block = find_bytes(existing, INSTALL_START_MARKER).is_some();
    if !has_managed_block && has_top_level_install(existing)? {
        if saved_command == Some(command) {
            return Ok(existing.to_vec());
        }
        bail!(
            "install.command already exists outside Pando's managed block; update it manually or move it between the guided installer markers"
        );
    }
    update_install_command(existing, command)
}

fn has_top_level_install(existing: &[u8]) -> Result<bool> {
    if existing.is_empty() {
        return Ok(false);
    }
    let document: serde_yaml::Value = serde_yaml::from_slice(existing)
        .context("failed to inspect install.command in the global configuration")?;
    let Some(mapping) = document.as_mapping() else {
        return Ok(false);
    };
    Ok(mapping.contains_key(serde_yaml::Value::String("install".to_owned())))
}

fn update_install_command(existing: &[u8], command: &str) -> Result<Vec<u8>> {
    let has_start = find_bytes(existing, INSTALL_START_MARKER).is_some();
    let has_end = find_bytes(existing, INSTALL_END_MARKER).is_some();
    if has_start != has_end {
        bail!("config.yaml contains an incomplete pando guided installer block");
    }

    let block = install_command_block(command)?;
    let mut output = Vec::with_capacity(existing.len() + block.len() + 1);
    let mut remaining = existing;
    let mut inserted = false;
    while let Some(start) = find_bytes(remaining, INSTALL_START_MARKER) {
        output.extend_from_slice(&remaining[..start]);
        let managed = &remaining[start..];
        let Some(relative_end) = find_bytes(managed, INSTALL_END_MARKER) else {
            bail!("config.yaml contains an unterminated pando guided installer block");
        };
        let mut after = relative_end + INSTALL_END_MARKER.len();
        if managed.get(after..after + 2) == Some(b"\r\n") {
            after += 2;
        } else if managed.get(after) == Some(&b'\n') {
            after += 1;
        }
        if !inserted {
            output.extend_from_slice(&block);
            inserted = true;
        }
        remaining = &managed[after..];
    }
    output.extend_from_slice(remaining);
    if !inserted {
        if !output.is_empty() && !output.ends_with(b"\n") {
            output.push(b'\n');
        }
        output.extend_from_slice(&block);
    }
    Ok(output)
}

fn config_home() -> Result<PathBuf> {
    if let Some(path) = nonempty_var("XDG_CONFIG_HOME") {
        return Ok(PathBuf::from(path));
    }
    Ok(home()?.join(".config"))
}

fn zshrc_path() -> Result<PathBuf> {
    if let Some(path) = nonempty_var("ZDOTDIR") {
        return Ok(PathBuf::from(path).join(".zshrc"));
    }
    Ok(home()?.join(".zshrc"))
}

fn home() -> Result<PathBuf> {
    nonempty_var("HOME")
        .map(PathBuf::from)
        .context("HOME is not set; cannot choose a zsh configuration location")
}

fn nonempty_var(name: &str) -> Option<std::ffi::OsString> {
    env::var_os(name).filter(|value| !value.is_empty())
}

fn update_config_scaffold(existing: &[u8]) -> Result<Vec<u8>> {
    let mut output = Vec::with_capacity(existing.len() + CONFIG_SCAFFOLD.len() + 1);
    let mut remaining = existing;
    let mut inserted = false;

    while let Some(start) = find_bytes(remaining, CONFIG_START_MARKER) {
        output.extend_from_slice(&remaining[..start]);
        let managed = &remaining[start..];
        let Some(relative_end) = find_bytes(managed, CONFIG_END_MARKER) else {
            bail!("config.yaml contains an unterminated pando configuration scaffold");
        };
        let mut after = relative_end + CONFIG_END_MARKER.len();
        if managed.get(after..after + 2) == Some(b"\r\n") {
            after += 2;
        } else if managed.get(after) == Some(&b'\n') {
            after += 1;
        }
        if !inserted {
            output.extend_from_slice(CONFIG_SCAFFOLD);
            inserted = true;
        }
        remaining = &managed[after..];
    }
    output.extend_from_slice(remaining);

    if !inserted {
        if !output.is_empty() && !output.ends_with(b"\n") {
            output.push(b'\n');
        }
        output.extend_from_slice(CONFIG_SCAFFOLD);
    }
    Ok(output)
}

fn source_block(integration_path: &Path) -> Vec<u8> {
    let mut block = Vec::new();
    block.extend_from_slice(START_MARKER);
    block.extend_from_slice(b"\nsource -- ");
    append_zsh_quoted(&mut block, integration_path.as_os_str());
    block.push(b'\n');
    block.extend_from_slice(END_MARKER);
    block.push(b'\n');
    block
}

fn append_zsh_quoted(output: &mut Vec<u8>, value: &OsStr) {
    output.push(b'\'');
    for byte in value.as_bytes() {
        if *byte == b'\'' {
            output.extend_from_slice(b"'\\''");
        } else {
            output.push(*byte);
        }
    }
    output.push(b'\'');
}

fn update_source_block(existing: &[u8], source_block: &[u8]) -> Result<Vec<u8>> {
    let mut output = Vec::with_capacity(existing.len() + source_block.len() + 1);
    let mut remaining = existing;
    let mut inserted = false;

    while let Some(start) = find_bytes(remaining, START_MARKER) {
        output.extend_from_slice(&remaining[..start]);
        let managed = &remaining[start..];
        let Some(relative_end) = find_bytes(managed, END_MARKER) else {
            bail!("{} contains an unterminated pando source block", ".zshrc");
        };
        let mut after = relative_end + END_MARKER.len();
        if managed.get(after..after + 2) == Some(b"\r\n") {
            after += 2;
        } else if managed.get(after) == Some(&b'\n') {
            after += 1;
        }
        if !inserted {
            output.extend_from_slice(source_block);
            inserted = true;
        }
        remaining = &managed[after..];
    }
    output.extend_from_slice(remaining);

    if !inserted {
        if !output.is_empty() && !output.ends_with(b"\n") {
            output.push(b'\n');
        }
        output.extend_from_slice(source_block);
    }
    Ok(output)
}

fn find_bytes(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    haystack
        .windows(needle.len())
        .position(|window| window == needle)
}

fn write_observed_target(path: &Path, observed: &TargetObservation, content: &[u8]) -> Result<()> {
    if !observation_matches(path, observed)? {
        bail!("destination changed during approved installation");
    }
    let destination = match observed {
        TargetObservation::Symlink { destination, .. } => destination,
        TargetObservation::Absent { .. } | TargetObservation::File { .. } => path,
    };
    write_atomic_file(destination, content)
}

fn write_atomic_file(path: &Path, content: &[u8]) -> Result<()> {
    let parent = path
        .parent()
        .with_context(|| format!("{} has no parent directory", path.display()))?;
    fs::create_dir_all(parent)
        .with_context(|| format!("failed to create directory {}", parent.display()))?;

    let existing_permissions = fs::metadata(path)
        .ok()
        .map(|metadata| metadata.permissions());
    for attempt in 0..100_u8 {
        let temporary = parent.join(format!(".pando.tmp.{}.{}", std::process::id(), attempt));
        let file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary);
        let mut file = match file {
            Ok(file) => file,
            Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => continue,
            Err(error) => return Err(error.into()),
        };
        let result = (|| -> Result<()> {
            file.write_all(content)?;
            file.sync_all()?;
            if let Some(permissions) = existing_permissions.clone() {
                file.set_permissions(permissions)?;
            }
            drop(file);
            fs::rename(&temporary, path)?;
            Ok(())
        })();
        if result.is_err() {
            let _ = fs::remove_file(&temporary);
        }
        return result;
    }
    bail!(
        "could not allocate a temporary file beside {}",
        path.display()
    )
}

#[cfg(test)]
mod tests {
    use std::{fs, os::unix::fs::PermissionsExt, path::Path};

    use super::{
        CONFIG_END_MARKER, CONFIG_START_MARKER, CommandWrite, END_MARKER, INSTALL_END_MARKER,
        INSTALL_START_MARKER, InstallApproval, InstallOutcome, InstallPlan, InstallProposal,
        InstallTarget, Observations, ProposedWrite, START_MARKER, agent_invocation,
        execute as execute_install, observe_target, persist_install_command,
        persist_proposed_command, update_config_scaffold, update_install_command,
        update_source_block, write_effect,
    };
    use crate::protocol::BytePath;

    fn execute(
        proposal: InstallProposal,
        approval: InstallApproval,
        plan: InstallPlan,
    ) -> InstallOutcome {
        execute_install(
            proposal,
            approval,
            plan,
            false,
            &mut Observations::captured(),
        )
    }

    #[test]
    fn config_scaffold_is_added_and_idempotent() {
        let existing = b"worktrees:\n  default-sort: path\n";
        let updated = update_config_scaffold(existing).unwrap();
        assert!(updated.starts_with(existing));
        assert_eq!(update_config_scaffold(&updated).unwrap(), updated);
        assert_eq!(count_marker(&updated, CONFIG_START_MARKER), 1);
        assert_eq!(count_marker(&updated, CONFIG_END_MARKER), 1);
    }

    #[test]
    fn guided_installer_command_is_added_updated_and_idempotent() {
        let existing = b"worktrees:\n  root: ../worktrees\n";
        let installed = update_install_command(existing, "pi").unwrap();
        assert!(installed.starts_with(existing));
        assert!(
            installed
                .windows(b"command: pi".len())
                .any(|value| value == b"command: pi")
        );
        assert_eq!(update_install_command(&installed, "pi").unwrap(), installed);

        let updated = update_install_command(&installed, "claude --model opus").unwrap();
        assert!(
            updated
                .windows(b"command: claude --model opus".len())
                .any(|value| value == b"command: claude --model opus")
        );
        assert_eq!(count_marker(&updated, INSTALL_START_MARKER), 1);
        assert_eq!(count_marker(&updated, INSTALL_END_MARKER), 1);
    }

    #[test]
    fn unmarked_install_command_is_preserved_without_creating_duplicate_yaml() {
        let existing = b"install:\n  command: claude\nworktrees:\n  root: ../worktrees\n";
        assert_eq!(
            persist_install_command(existing, Some("claude"), "claude").unwrap(),
            existing
        );
        assert!(
            persist_install_command(existing, Some("claude"), "pi")
                .unwrap_err()
                .to_string()
                .contains("outside Pando's managed block")
        );
    }

    #[test]
    fn command_persistence_rejects_a_concurrently_changed_configuration() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("config.yaml");
        fs::write(&path, b"worktrees:\n  root: old\n").unwrap();
        let proposal = CommandWrite {
            command: "pi".into(),
            write: Some(ProposedWrite {
                role: "guided command",
                path: path.clone(),
                desired: b"desired".to_vec(),
                observed: observe_target(&path).unwrap(),
                verb: "update",
            }),
        };
        fs::write(&path, b"worktrees:\n  root: concurrent\n").unwrap();
        let mut effect = write_effect(proposal.write.as_ref().unwrap());

        let error = persist_proposed_command(&proposal, Some(&mut effect)).unwrap_err();

        assert!(error.to_string().contains("changed after confirmation"));
        assert!(!effect.attempted);
        assert!(!effect.completed);
        assert_eq!(fs::read(path).unwrap(), b"worktrees:\n  root: concurrent\n");
    }

    #[test]
    fn command_persistence_noop_needs_no_effect() {
        let proposal = CommandWrite {
            command: "pi".into(),
            write: None,
        };

        persist_proposed_command(&proposal, None).unwrap();
    }

    #[test]
    fn guided_installer_rejects_an_orphaned_end_marker() {
        let existing = [INSTALL_END_MARKER, b"\n"].concat();
        assert!(
            update_install_command(&existing, "pi")
                .unwrap_err()
                .to_string()
                .contains("incomplete pando guided installer block")
        );
    }

    #[test]
    fn shell_operators_require_an_explicit_prompt_placeholder() {
        assert!(agent_invocation("claude | tee transcript", "configure").is_err());
        assert_eq!(
            agent_invocation("claude {prompt} | tee transcript", "configure").unwrap(),
            "exec claude 'configure' | tee transcript"
        );
        assert_eq!(
            agent_invocation("claude --model opus", "configure").unwrap(),
            "exec claude --model opus 'configure'"
        );
    }

    #[test]
    fn config_scaffold_replaces_only_its_managed_block() {
        let existing = [
            b"commit:\n  generation:\n    command: custom\n".as_slice(),
            CONFIG_START_MARKER,
            b"\n# old scaffold\n".as_slice(),
            CONFIG_END_MARKER,
            b"\n".as_slice(),
        ]
        .concat();
        let updated = update_config_scaffold(&existing).unwrap();
        assert!(updated.starts_with(b"commit:\n  generation:\n    command: custom\n"));
        assert_eq!(count_marker(&updated, CONFIG_START_MARKER), 1);
        assert_eq!(count_marker(&updated, CONFIG_END_MARKER), 1);
        assert!(
            !updated
                .windows(b"# old scaffold".len())
                .any(|window| window == b"# old scaffold")
        );
    }

    #[test]
    fn observation_delivery_and_replay_preserve_the_install_outcome() {
        let directory = tempfile::tempdir().unwrap();
        let captured_path = directory.path().join("captured");
        let human_path = directory.path().join("human");
        let startup_path = directory.path().join("startup");
        let mut captured_plan = test_plan(&captured_path);
        captured_plan.startup_path.clone_from(&startup_path);
        let mut human_plan = test_plan(&human_path);
        human_plan.startup_path.clone_from(&startup_path);

        let mut captured = Observations::captured();
        let captured_outcome = execute_install(
            proposal(
                &captured_path,
                observe_target(&captured_path).unwrap(),
                b"desired",
            ),
            InstallApproval(()),
            captured_plan,
            false,
            &mut captured,
        );
        let captured_events = captured.finish();

        let mut human = Observations::human();
        let human_outcome = execute_install(
            proposal(
                &human_path,
                observe_target(&human_path).unwrap(),
                b"desired",
            ),
            InstallApproval(()),
            human_plan,
            false,
            &mut human,
        );
        let human_events = human.finish();

        assert!(captured_outcome.result.is_ok());
        assert!(human_outcome.result.is_ok());
        assert_eq!(captured_outcome.effects.len(), human_outcome.effects.len());
        for (captured, human) in captured_outcome.effects.iter().zip(&human_outcome.effects) {
            assert_eq!(captured.action, human.action);
            assert_eq!(captured.attempted, human.attempted);
            assert_eq!(captured.completed, human.completed);
        }
        assert_eq!(human_events, captured_events);

        let mut replayed = Observations::captured();
        for event in &captured_events {
            replayed.emit(event.clone());
        }
        assert_eq!(replayed.finish(), captured_events);
    }

    #[test]
    fn execution_refuses_stale_content_before_attempting_the_write() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("config.yaml");
        fs::write(&path, b"observed").unwrap();
        let observed = observe_target(&path).unwrap();
        fs::write(&path, b"changed").unwrap();

        let outcome = execute(
            proposal(&path, observed, b"desired"),
            InstallApproval(()),
            test_plan(&path),
        );

        assert!(outcome.result.is_err());
        assert!(!outcome.effects[0].attempted);
        assert!(!outcome.effects[0].completed);
        assert_eq!(fs::read(path).unwrap(), b"changed");
    }

    #[test]
    fn execution_attributes_partial_effects_and_stops_at_a_stale_target() {
        let directory = tempfile::tempdir().unwrap();
        let first = directory.path().join("config.yaml");
        let second = directory.path().join("pando.zsh");
        fs::write(&second, b"observed").unwrap();
        let proposal = InstallProposal {
            writes: vec![
                proposed_write("configuration", &first, b"first"),
                proposed_write("integration", &second, b"second"),
            ],
        };
        fs::write(&second, b"stale").unwrap();

        let outcome = execute(proposal, InstallApproval(()), test_plan(&first));

        assert!(outcome.result.is_err());
        assert!(outcome.effects[0].attempted);
        assert!(outcome.effects[0].completed);
        assert!(!outcome.effects[1].attempted);
        assert!(!outcome.effects[1].completed);
        assert_eq!(fs::read(first).unwrap(), b"first");
        assert_eq!(fs::read(second).unwrap(), b"stale");
    }

    #[test]
    fn execution_detects_identity_changes_with_identical_bytes() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join(".zshrc");
        let replacement = directory.path().join("replacement");
        fs::write(&path, b"same").unwrap();
        let observed = observe_target(&path).unwrap();
        fs::write(&replacement, b"same").unwrap();
        fs::rename(&replacement, &path).unwrap();

        let outcome = execute(
            proposal(&path, observed, b"desired"),
            InstallApproval(()),
            test_plan(&path),
        );

        assert!(outcome.result.is_err());
        assert!(!outcome.effects[0].attempted);
        assert_eq!(fs::read(path).unwrap(), b"same");
    }

    #[test]
    fn execution_refuses_a_retargeted_symlink() {
        use std::os::unix::fs::symlink;

        let directory = tempfile::tempdir().unwrap();
        let first = directory.path().join("first");
        let second = directory.path().join("second");
        let path = directory.path().join(".zshrc");
        fs::write(&first, b"same").unwrap();
        fs::write(&second, b"same").unwrap();
        symlink(&first, &path).unwrap();
        let observed = observe_target(&path).unwrap();
        fs::remove_file(&path).unwrap();
        symlink(&second, &path).unwrap();

        let outcome = execute(
            proposal(&path, observed, b"desired"),
            InstallApproval(()),
            test_plan(&path),
        );

        assert!(outcome.result.is_err());
        assert!(!outcome.effects[0].attempted);
        assert_eq!(fs::read(first).unwrap(), b"same");
        assert_eq!(fs::read(second).unwrap(), b"same");
    }

    #[test]
    fn execution_refuses_a_new_parent_symlink_for_an_absent_target() {
        use std::os::unix::fs::symlink;

        let directory = tempfile::tempdir().unwrap();
        let approved_parent = directory.path().join("approved");
        let redirected_parent = directory.path().join("redirected");
        fs::create_dir(&approved_parent).unwrap();
        fs::create_dir(&redirected_parent).unwrap();
        let path = approved_parent.join("config.yaml");
        let observed = observe_target(&path).unwrap();
        fs::remove_dir(&approved_parent).unwrap();
        symlink(&redirected_parent, &approved_parent).unwrap();

        let outcome = execute(
            proposal(&path, observed, b"desired"),
            InstallApproval(()),
            test_plan(&path),
        );

        assert!(outcome.result.is_err());
        assert!(!outcome.effects[0].attempted);
        assert!(!redirected_parent.join("config.yaml").exists());
    }

    #[test]
    fn approved_write_preserves_observed_permissions() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join(".zshrc");
        fs::write(&path, b"old").unwrap();
        fs::set_permissions(&path, fs::Permissions::from_mode(0o640)).unwrap();
        let observed = observe_target(&path).unwrap();

        let outcome = execute(
            proposal(&path, observed, b"new"),
            InstallApproval(()),
            test_plan(&path),
        );

        assert!(outcome.result.is_ok());
        assert_eq!(
            fs::metadata(path).unwrap().permissions().mode() & 0o777,
            0o640
        );
    }

    fn proposal(
        path: &Path,
        observed: super::TargetObservation,
        desired: &[u8],
    ) -> InstallProposal {
        InstallProposal {
            writes: vec![ProposedWrite {
                role: "configuration",
                path: path.to_path_buf(),
                desired: desired.to_vec(),
                observed,
                verb: "update",
            }],
        }
    }

    fn proposed_write(role: &'static str, path: &Path, desired: &[u8]) -> ProposedWrite {
        ProposedWrite {
            role,
            path: path.to_path_buf(),
            desired: desired.to_vec(),
            observed: observe_target(path).unwrap(),
            verb: "write",
        }
    }

    fn test_plan(path: &Path) -> InstallPlan {
        let target = || InstallTarget {
            path: BytePath::path(path),
            would_change: true,
        };
        InstallPlan {
            changed: true,
            configuration: target(),
            integration: target(),
            startup: target(),
            config_path: path.to_path_buf(),
            integration_path: path.to_path_buf(),
            startup_path: path.to_path_buf(),
        }
    }

    fn count_marker(value: &[u8], marker: &[u8]) -> usize {
        value
            .windows(marker.len())
            .filter(|window| *window == marker)
            .count()
    }

    #[test]
    fn replacing_managed_content_preserves_unrelated_bytes() {
        let existing = [
            b"before\xff\n".as_slice(),
            START_MARKER,
            b"\nold\n".as_slice(),
            END_MARKER,
            b"\nafter\n".as_slice(),
        ]
        .concat();
        let desired = [START_MARKER, b"\nnew\n".as_slice(), END_MARKER, b"\n"].concat();
        let updated = update_source_block(&existing, &desired).unwrap();
        assert_eq!(
            updated,
            [b"before\xff\n".as_slice(), desired.as_slice(), b"after\n"].concat()
        );
    }

    #[test]
    fn duplicate_managed_blocks_are_normalized() {
        let block = [START_MARKER, b"\nold\n".as_slice(), END_MARKER, b"\n"].concat();
        let existing = [block.as_slice(), b"middle\n", block.as_slice()].concat();
        let desired = [START_MARKER, b"\nnew\n".as_slice(), END_MARKER, b"\n"].concat();
        let updated = update_source_block(&existing, &desired).unwrap();
        assert_eq!(updated, [desired.as_slice(), b"middle\n"].concat());
    }
}
