use std::{
    env,
    ffi::OsStr,
    fs::{self, OpenOptions},
    io::Write,
    os::unix::ffi::OsStrExt,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result, bail};
use cliclack::confirm;

use crate::ui;

const START_MARKER: &[u8] = b"# >>> worktrees shell integration >>>";
const END_MARKER: &[u8] = b"# <<< worktrees shell integration <<<";
const CONFIG_START_MARKER: &[u8] = b"# >>> worktrees configuration scaffold >>>";
const CONFIG_END_MARKER: &[u8] = b"# <<< worktrees configuration scaffold <<<";

const CONFIG_SCAFFOLD: &[u8] = br"# >>> worktrees configuration scaffold >>>
# Uncomment and customize these settings as needed.
#
# Worktree creation requires a placement root:
# worktrees:
#   root: ../worktrees
#   # Optional target branch. If omitted, Worktrees falls back to origin/HEAD,
#   # then local main, then local master:
#   target-branch: main
#
# Optional PR metadata generator. Required only when title or description is
# omitted from `worktrees pr create`:
# pr:
#   generation:
#     command: pi --no-session --no-tools
# <<< worktrees configuration scaffold <<<
";

const INTEGRATION: &[u8] = br#"# Generated by worktrees. Do not edit.
# The dispatcher deliberately avoids a leading underscore: that prefix is the
# zsh completion-function convention, and tools that capture a shell's function
# table (Claude Code's shell snapshots, for one) drop `_name` functions wholesale
# to skip the completion system. A dropped helper would leave `worktrees` and
# `wt` defined but calling a command that no longer exists.
worktrees_dispatch() {
  local executable="$1"
  shift
  local structured=false passthrough=false expect_format=false arg
  for arg in "$@"; do
    if [[ "$expect_format" == true ]]; then
      [[ "$arg" == json ]] && structured=true
      expect_format=false
      continue
    fi
    case "$arg" in
      --output|--input-output) expect_format=true ;;
      --output=json|--input-output=json) structured=true ;;
      -h|--help|-V|--version) passthrough=true ;;
    esac
  done
  if [[ ! -o interactive ]] || [[ "$structured" == true ]] || [[ "$passthrough" == true ]]; then
    command "$executable" "$@"
  elif [[ "$1" == "switch" || "$1" == "create" || "$1" == "remove" || "$1" == "merge" ]]; then
    local destination
    destination="$(command "$executable" "$@")"
    local exit_status=$?
    if [[ -n "$destination" ]]; then
      builtin cd -- "$destination" || return $?
    fi
    return $exit_status
  else
    command "$executable" "$@"
  fi
}

worktrees() { worktrees_dispatch worktrees "$@"; }
wt() { worktrees_dispatch wt "$@"; }

# Dynamic completion for both names. The registration script is generated on
# every shell start rather than cached: clap_complete gives no stability
# guarantee between the script it emits and the completion protocol the binary
# expects, so a cached script would silently break after a binary upgrade.
# Generating it costs one process spawn, measured under 3ms.
#
# `wt` is a symlink to the same binary, so one registration serves both names.
# The generated function is named `_clap_dynamic_completer_worktrees`; the
# leading underscore is the completion system's own convention here, unlike the
# dispatcher above, and a dropped snapshot copy only disables completion.
worktrees_register_completion() {
  (( $+functions[compdef] )) || return 1
  local script
  # Captured into a variable rather than `eval "$(... )"` directly: if the
  # binary is missing from PATH the command substitution yields an empty
  # string, and `eval ""` exits 0. That would report registration as
  # successful while leaving `_clap_dynamic_completer_worktrees` undefined,
  # so `compdef` below would bind both names to a function that never
  # existed and the precmd retry would never re-arm.
  script="$(_WORKTREES_COMPLETE=zsh command worktrees 2>/dev/null)" || return 1
  [[ -n "$script" ]] || return 1
  eval "$script"
  compdef _clap_dynamic_completer_worktrees wt
  return 0
}

if [[ -o interactive ]]; then
  if ! worktrees_register_completion; then
    # `compinit` has not run yet, so retry once after startup finishes.
    worktrees_deferred_completion() {
      worktrees_register_completion
      add-zsh-hook -d precmd worktrees_deferred_completion
      unfunction worktrees_deferred_completion
    }
    autoload -Uz add-zsh-hook && add-zsh-hook precmd worktrees_deferred_completion
  fi
fi
"#;

/// Returns the deterministic installation plan used by JSON previews.
///
/// # Errors
/// Returns an error when paths or existing installation files cannot be read.
pub fn json_plan() -> Result<serde_json::Value> {
    let config_path = config_home()?.join("worktrees/config.yaml");
    let integration_path = config_home()?.join("worktrees/worktrees.zsh");
    let zshrc_path = zshrc_path()?;
    let source_block = source_block(&integration_path);
    let existing_config = read_optional(&config_path)?;
    let existing_integration = read_optional(&integration_path)?;
    let existing_zshrc = read_optional(&zshrc_path)?;
    let desired_config = update_config_scaffold(&existing_config)?;
    let desired_zshrc = update_source_block(&existing_zshrc, &source_block)?;
    let config_changed = existing_config != desired_config;
    let integration_changed = existing_integration != INTEGRATION;
    let startup_changed = existing_zshrc != desired_zshrc;
    Ok(
        serde_json::json!({"changed":config_changed || integration_changed || startup_changed,"configuration":{"path":crate::protocol::BytePath::path(&config_path),"would_change":config_changed},"integration":{"path":crate::protocol::BytePath::path(&integration_path),"would_change":integration_changed},"startup":{"path":crate::protocol::BytePath::path(&zshrc_path),"would_change":startup_changed}}),
    )
}

/// Renders the installation plan without writing or prompting.
///
/// # Errors
/// Returns an error when paths or existing installation files cannot be read or rendered.
pub fn preview() -> Result<()> {
    let plan = json_plan()?;
    ui::info(ui::heading_style().apply_to("Planned zsh integration changes:"))?;
    for key in ["integration", "startup"] {
        let item = &plan[key];
        let state = if item["would_change"].as_bool().unwrap_or(false) {
            "would update"
        } else {
            "already current"
        };
        let path = item["path"]["value"].as_str().unwrap_or("<non-UTF-8 path>");
        ui::step(format!(
            "{state}: {}",
            ui::worktree_data_style().apply_to(path)
        ))?;
    }
    ui::finish(ui::success_style().apply_to("Installation preview complete."))
}

/// Installs or updates the managed zsh integration after confirmation.
///
/// # Errors
///
/// Returns an error when environment paths cannot be resolved, existing files
/// cannot be inspected, confirmation cannot be read, or a planned write fails.
pub fn run() -> Result<()> {
    let config_path = config_home()?.join("worktrees/config.yaml");
    let integration_path = config_home()?.join("worktrees/worktrees.zsh");
    let zshrc_path = zshrc_path()?;
    let source_block = source_block(&integration_path);

    let existing_config = read_optional(&config_path)?;
    let existing_integration = read_optional(&integration_path)?;
    let existing_zshrc = read_optional(&zshrc_path)?;
    let desired_config = update_config_scaffold(&existing_config)?;
    let desired_zshrc = update_source_block(&existing_zshrc, &source_block)?;
    let config_changed = existing_config != desired_config;
    let integration_changed = existing_integration != INTEGRATION;
    let zshrc_changed = existing_zshrc != desired_zshrc;

    if !config_changed && !integration_changed && !zshrc_changed {
        ui::info("The worktrees installation is already current; no changes are required.")?;
        return ui::finish(
            ui::success_style().apply_to("Worktrees installation is already current."),
        );
    }

    ui::ensure_interactive("worktrees installation requires confirmation")?;
    ui::info(ui::heading_style().apply_to("Planned worktrees installation changes:"))?;
    if config_changed {
        ui::step(format!(
            "write {}",
            ui::worktree_data_style().apply_to(config_path.display())
        ))?;
    }
    if integration_changed {
        ui::step(format!(
            "write {}",
            ui::worktree_data_style().apply_to(integration_path.display())
        ))?;
    }
    if zshrc_changed {
        ui::step(format!(
            "update {}",
            ui::worktree_data_style().apply_to(zshrc_path.display())
        ))?;
    }

    let confirmed = ui::prompt_result(
        confirm("Apply these changes?")
            .initial_value(false)
            .interact(),
        "installation cancelled",
        "failed to read installation confirmation",
    )?;
    if !confirmed {
        return Err(ui::declined_noop(
            "Installation declined; no files were changed.",
            "Zsh integration was not installed.",
        ));
    }

    if config_changed {
        write_atomic(&config_path, &desired_config)
            .with_context(|| format!("failed to update {}", config_path.display()))?;
    }
    if integration_changed {
        write_atomic(&integration_path, INTEGRATION)
            .with_context(|| format!("failed to write {}", integration_path.display()))?;
    }
    if zshrc_changed {
        write_atomic(&zshrc_path, &desired_zshrc)
            .with_context(|| format!("failed to update {}", zshrc_path.display()))?;
    }

    ui::success("Installed zsh integration.")?;
    ui::info(format!(
        "Restart zsh or run: source {}",
        ui::worktree_data_style().apply_to(zshrc_path.display())
    ))?;
    ui::finish(ui::success_style().apply_to("Zsh integration installed."))
}

fn config_home() -> Result<PathBuf> {
    if let Some(path) = nonempty_var("XDG_CONFIG_HOME") {
        return Ok(PathBuf::from(path));
    }
    Ok(home()?.join(".config"))
}

fn zshrc_path() -> Result<PathBuf> {
    if let Some(path) = nonempty_var("ZDOTDIR") {
        return Ok(PathBuf::from(path).join(".zshrc"));
    }
    Ok(home()?.join(".zshrc"))
}

fn home() -> Result<PathBuf> {
    nonempty_var("HOME")
        .map(PathBuf::from)
        .context("HOME is not set; cannot choose a zsh configuration location")
}

fn nonempty_var(name: &str) -> Option<std::ffi::OsString> {
    env::var_os(name).filter(|value| !value.is_empty())
}

fn read_optional(path: &Path) -> Result<Vec<u8>> {
    match fs::read(path) {
        Ok(content) => Ok(content),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(Vec::new()),
        Err(error) => {
            Err(error).with_context(|| format!("failed to read existing file {}", path.display()))
        }
    }
}

fn update_config_scaffold(existing: &[u8]) -> Result<Vec<u8>> {
    let mut output = Vec::with_capacity(existing.len() + CONFIG_SCAFFOLD.len() + 1);
    let mut remaining = existing;
    let mut inserted = false;

    while let Some(start) = find_bytes(remaining, CONFIG_START_MARKER) {
        output.extend_from_slice(&remaining[..start]);
        let managed = &remaining[start..];
        let Some(relative_end) = find_bytes(managed, CONFIG_END_MARKER) else {
            bail!("config.yaml contains an unterminated worktrees configuration scaffold");
        };
        let mut after = relative_end + CONFIG_END_MARKER.len();
        if managed.get(after..after + 2) == Some(b"\r\n") {
            after += 2;
        } else if managed.get(after) == Some(&b'\n') {
            after += 1;
        }
        if !inserted {
            output.extend_from_slice(CONFIG_SCAFFOLD);
            inserted = true;
        }
        remaining = &managed[after..];
    }
    output.extend_from_slice(remaining);

    if !inserted {
        if !output.is_empty() && !output.ends_with(b"\n") {
            output.push(b'\n');
        }
        output.extend_from_slice(CONFIG_SCAFFOLD);
    }
    Ok(output)
}

fn source_block(integration_path: &Path) -> Vec<u8> {
    let mut block = Vec::new();
    block.extend_from_slice(START_MARKER);
    block.extend_from_slice(b"\nsource -- ");
    append_zsh_quoted(&mut block, integration_path.as_os_str());
    block.push(b'\n');
    block.extend_from_slice(END_MARKER);
    block.push(b'\n');
    block
}

fn append_zsh_quoted(output: &mut Vec<u8>, value: &OsStr) {
    output.push(b'\'');
    for byte in value.as_bytes() {
        if *byte == b'\'' {
            output.extend_from_slice(b"'\\''");
        } else {
            output.push(*byte);
        }
    }
    output.push(b'\'');
}

fn update_source_block(existing: &[u8], source_block: &[u8]) -> Result<Vec<u8>> {
    let mut output = Vec::with_capacity(existing.len() + source_block.len() + 1);
    let mut remaining = existing;
    let mut inserted = false;

    while let Some(start) = find_bytes(remaining, START_MARKER) {
        output.extend_from_slice(&remaining[..start]);
        let managed = &remaining[start..];
        let Some(relative_end) = find_bytes(managed, END_MARKER) else {
            bail!(
                "{} contains an unterminated worktrees source block",
                ".zshrc"
            );
        };
        let mut after = relative_end + END_MARKER.len();
        if managed.get(after..after + 2) == Some(b"\r\n") {
            after += 2;
        } else if managed.get(after) == Some(&b'\n') {
            after += 1;
        }
        if !inserted {
            output.extend_from_slice(source_block);
            inserted = true;
        }
        remaining = &managed[after..];
    }
    output.extend_from_slice(remaining);

    if !inserted {
        if !output.is_empty() && !output.ends_with(b"\n") {
            output.push(b'\n');
        }
        output.extend_from_slice(source_block);
    }
    Ok(output)
}

fn find_bytes(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    haystack
        .windows(needle.len())
        .position(|window| window == needle)
}

fn write_atomic(path: &Path, content: &[u8]) -> Result<()> {
    let destination = match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_symlink() => fs::canonicalize(path)
            .with_context(|| format!("refusing to replace broken symlink {}", path.display()))?,
        Ok(_) => path.to_path_buf(),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => path.to_path_buf(),
        Err(error) => {
            return Err(error)
                .with_context(|| format!("failed to inspect destination {}", path.display()));
        }
    };
    write_atomic_file(&destination, content)
}

fn write_atomic_file(path: &Path, content: &[u8]) -> Result<()> {
    let parent = path
        .parent()
        .with_context(|| format!("{} has no parent directory", path.display()))?;
    fs::create_dir_all(parent)
        .with_context(|| format!("failed to create directory {}", parent.display()))?;

    let existing_permissions = fs::metadata(path)
        .ok()
        .map(|metadata| metadata.permissions());
    for attempt in 0..100_u8 {
        let temporary = parent.join(format!(".worktrees.tmp.{}.{}", std::process::id(), attempt));
        let file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary);
        let mut file = match file {
            Ok(file) => file,
            Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => continue,
            Err(error) => return Err(error.into()),
        };
        let result = (|| -> Result<()> {
            file.write_all(content)?;
            file.sync_all()?;
            if let Some(permissions) = existing_permissions.clone() {
                file.set_permissions(permissions)?;
            }
            drop(file);
            fs::rename(&temporary, path)?;
            Ok(())
        })();
        if result.is_err() {
            let _ = fs::remove_file(&temporary);
        }
        return result;
    }
    bail!(
        "could not allocate a temporary file beside {}",
        path.display()
    )
}

#[cfg(test)]
mod tests {
    use super::{
        CONFIG_END_MARKER, CONFIG_START_MARKER, END_MARKER, START_MARKER, update_config_scaffold,
        update_source_block,
    };

    #[test]
    fn config_scaffold_is_added_and_idempotent() {
        let existing = b"worktrees:\n  default-sort: path\n";
        let updated = update_config_scaffold(existing).unwrap();
        assert!(updated.starts_with(existing));
        assert_eq!(update_config_scaffold(&updated).unwrap(), updated);
        assert_eq!(count_marker(&updated, CONFIG_START_MARKER), 1);
        assert_eq!(count_marker(&updated, CONFIG_END_MARKER), 1);
    }

    #[test]
    fn config_scaffold_replaces_only_its_managed_block() {
        let existing = [
            b"commit:\n  generation:\n    command: custom\n".as_slice(),
            CONFIG_START_MARKER,
            b"\n# old scaffold\n".as_slice(),
            CONFIG_END_MARKER,
            b"\n".as_slice(),
        ]
        .concat();
        let updated = update_config_scaffold(&existing).unwrap();
        assert!(updated.starts_with(b"commit:\n  generation:\n    command: custom\n"));
        assert_eq!(count_marker(&updated, CONFIG_START_MARKER), 1);
        assert_eq!(count_marker(&updated, CONFIG_END_MARKER), 1);
        assert!(
            !updated
                .windows(b"# old scaffold".len())
                .any(|window| window == b"# old scaffold")
        );
    }

    fn count_marker(value: &[u8], marker: &[u8]) -> usize {
        value
            .windows(marker.len())
            .filter(|window| *window == marker)
            .count()
    }

    #[test]
    fn replacing_managed_content_preserves_unrelated_bytes() {
        let existing = [
            b"before\xff\n".as_slice(),
            START_MARKER,
            b"\nold\n".as_slice(),
            END_MARKER,
            b"\nafter\n".as_slice(),
        ]
        .concat();
        let desired = [START_MARKER, b"\nnew\n".as_slice(), END_MARKER, b"\n"].concat();
        let updated = update_source_block(&existing, &desired).unwrap();
        assert_eq!(
            updated,
            [b"before\xff\n".as_slice(), desired.as_slice(), b"after\n"].concat()
        );
    }

    #[test]
    fn duplicate_managed_blocks_are_normalized() {
        let block = [START_MARKER, b"\nold\n".as_slice(), END_MARKER, b"\n"].concat();
        let existing = [block.as_slice(), b"middle\n", block.as_slice()].concat();
        let desired = [START_MARKER, b"\nnew\n".as_slice(), END_MARKER, b"\n"].concat();
        let updated = update_source_block(&existing, &desired).unwrap();
        assert_eq!(updated, [desired.as_slice(), b"middle\n"].concat());
    }
}
