use std::{
    env,
    ffi::OsStr,
    fs::{self, OpenOptions},
    io::Write,
    os::unix::ffi::OsStrExt,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result, bail};
use cliclack::confirm;

use crate::ui;

const START_MARKER: &[u8] = b"# >>> worktrees shell integration >>>";
const END_MARKER: &[u8] = b"# <<< worktrees shell integration <<<";

const INTEGRATION: &[u8] = br#"# Generated by worktrees. Do not edit.
worktrees() {
  if [[ "$1" == "switch" || "$1" == "remove" || "$1" == "merge" ]]; then
    local destination
    destination="$(command worktrees "$@")"
    local exit_status=$?
    if [[ -n "$destination" ]]; then
      builtin cd -- "$destination" || return $?
    fi
    return $exit_status
  else
    command worktrees "$@"
  fi
}

# Worktrunk currently owns `wt`. To adopt that short name in the future,
# uncomment the following wrapper after resolving the command conflict:
# wt() { worktrees "$@"; }
"#;

/// Installs or updates the managed zsh integration after confirmation.
///
/// # Errors
///
/// Returns an error when environment paths cannot be resolved, existing files
/// cannot be inspected, confirmation cannot be read, or a planned write fails.
pub fn run() -> Result<()> {
    let integration_path = config_home()?.join("worktrees/worktrees.zsh");
    let zshrc_path = zshrc_path()?;
    let source_block = source_block(&integration_path);

    let existing_integration = read_optional(&integration_path)?;
    let existing_zshrc = read_optional(&zshrc_path)?;
    let desired_zshrc = update_source_block(&existing_zshrc, &source_block)?;
    let integration_changed = existing_integration != INTEGRATION;
    let zshrc_changed = existing_zshrc != desired_zshrc;

    if !integration_changed && !zshrc_changed {
        ui::info("The worktrees zsh integration is already current; no changes are required.")?;
        return ui::finish(ui::success_style().apply_to("Zsh integration is already current."));
    }

    ui::info(ui::heading_style().apply_to("Planned zsh integration changes:"))?;
    if integration_changed {
        ui::step(format!(
            "write {}",
            ui::worktree_data_style().apply_to(integration_path.display())
        ))?;
    }
    if zshrc_changed {
        ui::step(format!(
            "update {}",
            ui::worktree_data_style().apply_to(zshrc_path.display())
        ))?;
    }

    let confirmed = confirm("Apply these changes?")
        .initial_value(false)
        .interact()
        .context("failed to read installation confirmation")?;
    if !confirmed {
        ui::warning("Installation cancelled; no files were changed.")?;
        return ui::finish(ui::warning_style().apply_to("Zsh integration installation cancelled."));
    }

    if integration_changed {
        write_atomic(&integration_path, INTEGRATION)
            .with_context(|| format!("failed to write {}", integration_path.display()))?;
    }
    if zshrc_changed {
        write_atomic(&zshrc_path, &desired_zshrc)
            .with_context(|| format!("failed to update {}", zshrc_path.display()))?;
    }

    ui::success("Installed zsh integration.")?;
    ui::info(format!(
        "Restart zsh or run: source {}",
        ui::worktree_data_style().apply_to(zshrc_path.display())
    ))?;
    ui::finish(ui::success_style().apply_to("Zsh integration installed."))
}

fn config_home() -> Result<PathBuf> {
    if let Some(path) = nonempty_var("XDG_CONFIG_HOME") {
        return Ok(PathBuf::from(path));
    }
    Ok(home()?.join(".config"))
}

fn zshrc_path() -> Result<PathBuf> {
    if let Some(path) = nonempty_var("ZDOTDIR") {
        return Ok(PathBuf::from(path).join(".zshrc"));
    }
    Ok(home()?.join(".zshrc"))
}

fn home() -> Result<PathBuf> {
    nonempty_var("HOME")
        .map(PathBuf::from)
        .context("HOME is not set; cannot choose a zsh configuration location")
}

fn nonempty_var(name: &str) -> Option<std::ffi::OsString> {
    env::var_os(name).filter(|value| !value.is_empty())
}

fn read_optional(path: &Path) -> Result<Vec<u8>> {
    match fs::read(path) {
        Ok(content) => Ok(content),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(Vec::new()),
        Err(error) => {
            Err(error).with_context(|| format!("failed to read existing file {}", path.display()))
        }
    }
}

fn source_block(integration_path: &Path) -> Vec<u8> {
    let mut block = Vec::new();
    block.extend_from_slice(START_MARKER);
    block.extend_from_slice(b"\nsource -- ");
    append_zsh_quoted(&mut block, integration_path.as_os_str());
    block.push(b'\n');
    block.extend_from_slice(END_MARKER);
    block.push(b'\n');
    block
}

fn append_zsh_quoted(output: &mut Vec<u8>, value: &OsStr) {
    output.push(b'\'');
    for byte in value.as_bytes() {
        if *byte == b'\'' {
            output.extend_from_slice(b"'\\''");
        } else {
            output.push(*byte);
        }
    }
    output.push(b'\'');
}

fn update_source_block(existing: &[u8], source_block: &[u8]) -> Result<Vec<u8>> {
    let mut output = Vec::with_capacity(existing.len() + source_block.len() + 1);
    let mut remaining = existing;
    let mut inserted = false;

    while let Some(start) = find_bytes(remaining, START_MARKER) {
        output.extend_from_slice(&remaining[..start]);
        let managed = &remaining[start..];
        let Some(relative_end) = find_bytes(managed, END_MARKER) else {
            bail!(
                "{} contains an unterminated worktrees source block",
                ".zshrc"
            );
        };
        let mut after = relative_end + END_MARKER.len();
        if managed.get(after..after + 2) == Some(b"\r\n") {
            after += 2;
        } else if managed.get(after) == Some(&b'\n') {
            after += 1;
        }
        if !inserted {
            output.extend_from_slice(source_block);
            inserted = true;
        }
        remaining = &managed[after..];
    }
    output.extend_from_slice(remaining);

    if !inserted {
        if !output.is_empty() && !output.ends_with(b"\n") {
            output.push(b'\n');
        }
        output.extend_from_slice(source_block);
    }
    Ok(output)
}

fn find_bytes(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    haystack
        .windows(needle.len())
        .position(|window| window == needle)
}

fn write_atomic(path: &Path, content: &[u8]) -> Result<()> {
    let destination = match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_symlink() => fs::canonicalize(path)
            .with_context(|| format!("refusing to replace broken symlink {}", path.display()))?,
        Ok(_) => path.to_path_buf(),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => path.to_path_buf(),
        Err(error) => {
            return Err(error)
                .with_context(|| format!("failed to inspect destination {}", path.display()));
        }
    };
    write_atomic_file(&destination, content)
}

fn write_atomic_file(path: &Path, content: &[u8]) -> Result<()> {
    let parent = path
        .parent()
        .with_context(|| format!("{} has no parent directory", path.display()))?;
    fs::create_dir_all(parent)
        .with_context(|| format!("failed to create directory {}", parent.display()))?;

    let existing_permissions = fs::metadata(path)
        .ok()
        .map(|metadata| metadata.permissions());
    for attempt in 0..100_u8 {
        let temporary = parent.join(format!(".worktrees.tmp.{}.{}", std::process::id(), attempt));
        let file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary);
        let mut file = match file {
            Ok(file) => file,
            Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => continue,
            Err(error) => return Err(error.into()),
        };
        let result = (|| -> Result<()> {
            file.write_all(content)?;
            file.sync_all()?;
            if let Some(permissions) = existing_permissions.clone() {
                file.set_permissions(permissions)?;
            }
            drop(file);
            fs::rename(&temporary, path)?;
            Ok(())
        })();
        if result.is_err() {
            let _ = fs::remove_file(&temporary);
        }
        return result;
    }
    bail!(
        "could not allocate a temporary file beside {}",
        path.display()
    )
}

#[cfg(test)]
mod tests {
    use super::{END_MARKER, START_MARKER, update_source_block};

    #[test]
    fn replacing_managed_content_preserves_unrelated_bytes() {
        let existing = [
            b"before\xff\n".as_slice(),
            START_MARKER,
            b"\nold\n".as_slice(),
            END_MARKER,
            b"\nafter\n".as_slice(),
        ]
        .concat();
        let desired = [START_MARKER, b"\nnew\n".as_slice(), END_MARKER, b"\n"].concat();
        let updated = update_source_block(&existing, &desired).unwrap();
        assert_eq!(
            updated,
            [b"before\xff\n".as_slice(), desired.as_slice(), b"after\n"].concat()
        );
    }

    #[test]
    fn duplicate_managed_blocks_are_normalized() {
        let block = [START_MARKER, b"\nold\n".as_slice(), END_MARKER, b"\n"].concat();
        let existing = [block.as_slice(), b"middle\n", block.as_slice()].concat();
        let desired = [START_MARKER, b"\nnew\n".as_slice(), END_MARKER, b"\n"].concat();
        let updated = update_source_block(&existing, &desired).unwrap();
        assert_eq!(updated, [desired.as_slice(), b"middle\n"].concat());
    }
}
